/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package B1805812;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Aurora
 */
public class b1805812 extends javax.swing.JFrame {

    /**
     * Creates new form ql
     */
    public b1805812() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfmh = new javax.swing.JTextField();
        tfth = new javax.swing.JTextField();
        cblh = new javax.swing.JComboBox<>();
        cbdv = new javax.swing.JComboBox<>();
        btdv = new javax.swing.JButton();
        bthb = new javax.swing.JButton();
        tfdg = new javax.swing.JTextField();
        day = new javax.swing.JTextField();
        cbsx = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dat ve xe khach");

        jLabel1.setText("Mã hàng hóa");

        jLabel2.setText("Tên hàng");

        jLabel3.setText("Loại hàng");

        jLabel4.setText("Nhà sản xuất");

        jLabel5.setText("Đơn vị tính");

        jLabel6.setText("Đơn giá");

        jLabel7.setText("Ngày nhập hàng");

        tfmh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmhActionPerformed(evt);
            }
        });

        tfth.setToolTipText("");

        cblh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Điện thoại", "Máy tính", "Tivi" }));
        cblh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblhActionPerformed(evt);
            }
        });

        cbdv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cái", "Chiếc" }));

        btdv.setText("Thêm mới");
        btdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdvActionPerformed(evt);
            }
        });

        bthb.setText("Hủy");
        bthb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthbActionPerformed(evt);
            }
        });

        cbsx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sharp", "Samsung", "Toshiba" }));
        cbsx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cblh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbdv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbsx, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 67, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btdv)
                                .addGap(91, 91, 91)
                                .addComponent(bthb))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfmh, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfth, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfmh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cblh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cbdv, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tfdg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btdv)
                    .addComponent(bthb))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Connection con;


    private void tfmhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmhActionPerformed

    }//GEN-LAST:event_tfmhActionPerformed

    private void bthbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthbActionPerformed
        tfmh.setText("");
        tfth.setText("");
        cblh.setSelectedIndex(0);
        cbsx.setSelectedIndex(0);
        cbdv.setSelectedIndex(0);
        tfdg.setText("");
        day.setText("");


    }//GEN-LAST:event_bthbActionPerformed

    private void cblhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cblhActionPerformed
    int i = 0;
    private void btdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdvActionPerformed

        if (i == 0) {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String dbUrl = "jdbc:sqlserver://localhost:1433;databaseName=thi;user=sa;password=sa2008";
                con = DriverManager.getConnection(dbUrl);
                JOptionPane.showMessageDialog(this, "Đã thiết lập kết nối lần đầu thành công!");
                i = 1;
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

        if (!(tfmh.getText().charAt(0) == 'H') || !(tfmh.getText().length() == 6)) {
            JOptionPane.showMessageDialog(rootPane, "Mã hàng hóa phải bắt đầu bằng H và có 6 ký tự!");
            return;
        }
        if (tfth.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Tên hàng không được rỗng!");
            return;
        }
        if (Integer.parseInt(tfdg.getText()) <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Đơn giá phải lớn hơn 0!");
            return;
        }
        date dayy = new date();
        try {
            dayy.setDay(new SimpleDateFormat("dd/MM/yyyy").parse(day.getText()));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        
        long millis=System.currentTimeMillis();  
        java.sql.Date date=new java.sql.Date(millis);  
        System.out.println(date);  
        
        
        if ((date.compareTo(dayy.getday()))>0) {
            JOptionPane.showMessageDialog(rootPane, "Thời gian phải lớn hơn hôm nay!");
            return;
        }

        try {
            String sql = "INSERT INTO muahang(mahang, tenhang, loaihang, nhasx, donvi, dongia, ngaynhap)" + "VALUES(?,?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, tfmh.getText());
            ps.setString(2, tfth.getText());
            String lh = cblh.getSelectedItem().toString();
            ps.setString(3, lh);
            String nsx = cbsx.getSelectedItem().toString();
            ps.setString(4, nsx);
            String dv = cbdv.getSelectedItem().toString();
            ps.setString(5, dv);
            ps.setString(6, tfdg.getText());
            ps.setDate(7, new Date(dayy.getday().getTime()));
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Đã lưu vào cơ sở dữ liệu");

            System.out.println(
                              "Mã hàng:" + tfmh.getText()
                              + "\nTên hàng:" + tfth.getText()
                              + "\nLoại hàng" + cblh.getSelectedItem().toString()
                              + "\nNhà sản xuất:" + cbsx.getSelectedItem().toString()
                              + "\nĐơn vị tính" + cbdv.getSelectedItem().toString()
                              + "\nĐơn giá:" + tfdg.getText()
                              + "\nNgày nhập hàng:" + day.getText()
            );

        } catch (Exception e) {
            e.printStackTrace();
//            JOptionPane.showMessageDialog(rootPane, "Lỗi!");
        }


    }//GEN-LAST:event_btdvActionPerformed

    private void cbsxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(b1805812.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(b1805812.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(b1805812.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(b1805812.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new b1805812().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdv;
    private javax.swing.JButton bthb;
    private javax.swing.JComboBox<String> cbdv;
    private javax.swing.JComboBox<String> cblh;
    private javax.swing.JComboBox<String> cbsx;
    private javax.swing.JTextField day;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField tfdg;
    private javax.swing.JTextField tfmh;
    private javax.swing.JTextField tfth;
    // End of variables declaration//GEN-END:variables
}
