package dat_hang;

import java.text.SimpleDateFormat;
import java.util.Calendar;

public class main1 extends javax.swing.JFrame {

    int[] nuockt = new int[12];
    int[] tt = new int[17];
    float giamgia;

    /**
     * Creates new form Caffe
     */
    public main1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tong = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ktsl = new javax.swing.JSpinner();
        jPanel11 = new javax.swing.JPanel();
        gt14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ktcb = new javax.swing.JCheckBox();
        jLabel35 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cscb = new javax.swing.JCheckBox();
        mycb = new javax.swing.JCheckBox();
        buncb = new javax.swing.JCheckBox();
        htcb = new javax.swing.JCheckBox();
        stingcb = new javax.swing.JCheckBox();
        tdsl = new javax.swing.JSpinner();
        tssl = new javax.swing.JSpinner();
        stsl = new javax.swing.JSpinner();
        nesl = new javax.swing.JSpinner();
        xxsl = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        gt9 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        gt5 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        gt6 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        gt7 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        gt8 = new javax.swing.JLabel();
        panelcap = new javax.swing.JPanel();
        cpcb = new javax.swing.JCheckBox();
        ddcb = new javax.swing.JCheckBox();
        sdcb = new javax.swing.JCheckBox();
        mccb = new javax.swing.JCheckBox();
        banhcb = new javax.swing.JCheckBox();
        cpsl = new javax.swing.JSpinner();
        ddsl = new javax.swing.JSpinner();
        banhsl = new javax.swing.JSpinner();
        mcsl = new javax.swing.JSpinner();
        sdsl = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        gt1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        gt2 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        gt3 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        gt4 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        gt0 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hoadon = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gianuoc = new javax.swing.JPanel();
        gt10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        gt11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        gt13 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        gt12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ddsl2 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel2.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("  Menu ");

        tong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dat_hang/calculator (1) (1).png"))); // NOI18N
        tong.setText("Tính Tổng");
        tong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tongActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dat_hang/xoa.png"))); // NOI18N
        jButton2.setText("Xóa");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dat_hang/bill.png"))); // NOI18N
        jButton3.setText("Xác Nhận");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dat_hang/delete (1).png"))); // NOI18N
        jButton4.setText("Thoát");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dat_hang/coffee (3).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addComponent(tong, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 100));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Tổng tiền cuối:");

        ktsl.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gt14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gt14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gt14.setLabelFor(cpcb);
        gt14.setText("0");
        gt14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gt14, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(gt14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("₫");

        ktcb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ktcb.setText("Khẩu trang");
        ktcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ktcbActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("(1.000 ₫)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(59, 59, 59)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ktcb)
                        .addGap(18, 18, 18)
                        .addComponent(ktsl, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel35)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ktsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ktcb)
                    .addComponent(jLabel35))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 380, 280));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cscb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cscb.setText("Cơm Sườn");
        cscb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cscbActionPerformed(evt);
            }
        });
        jPanel1.add(cscb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        mycb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mycb.setText("Mỳ Bò");
        mycb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mycbActionPerformed(evt);
            }
        });
        jPanel1.add(mycb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, -1, -1));

        buncb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buncb.setText("Bún Thịt Nướng");
        buncb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buncbActionPerformed(evt);
            }
        });
        jPanel1.add(buncb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, -1, -1));

        htcb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        htcb.setText("Hủ Tiếu");
        htcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htcbActionPerformed(evt);
            }
        });
        jPanel1.add(htcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 30));

        stingcb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stingcb.setText("Sting Dâu");
        stingcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stingcbActionPerformed(evt);
            }
        });
        jPanel1.add(stingcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 208, -1, -1));

        tdsl.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        tdsl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tdslStateChanged(evt);
            }
        });
        jPanel1.add(tdsl, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 36, 68, -1));

        tssl.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        tssl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tsslStateChanged(evt);
            }
        });
        jPanel1.add(tssl, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 80, 68, -1));

        stsl.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        stsl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                stslStateChanged(evt);
            }
        });
        jPanel1.add(stsl, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 124, 68, -1));

        nesl.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        nesl.setToolTipText("");
        nesl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                neslStateChanged(evt);
            }
        });
        jPanel1.add(nesl, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 168, 68, -1));

        xxsl.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        xxsl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                xxslStateChanged(evt);
            }
        });
        jPanel1.add(xxsl, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 212, 68, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("(15.000 ₫)");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 38, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("(10.000 ₫)");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 214, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("(14.000 ₫)");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 170, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("(16.000 ₫)");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 126, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("(18.000 ₫)");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 82, -1, -1));

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gt9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gt9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gt9.setLabelFor(cpcb);
        gt9.setText("0");
        gt9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt9, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 111, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("₫");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gt5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gt5.setLabelFor(cpcb);
        gt5.setText("0");
        gt5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt5, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 32, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("₫");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 38, -1, -1));

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gt6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gt6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gt6.setLabelFor(cpcb);
        gt6.setText("0");
        gt6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt6, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 76, 111, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("₫");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 82, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("₫");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 173, -1, -1));

        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gt7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gt7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gt7.setLabelFor(cpcb);
        gt7.setText("0");
        gt7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt7, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 111, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("₫");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 117, -1, -1));

        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gt8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gt8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gt8.setLabelFor(cpcb);
        gt8.setText("0");
        gt8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt8, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 167, 111, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 490, 280));

        panelcap.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        cpcb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cpcb.setText("Cà phê Cappuccino");
        cpcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpcbActionPerformed(evt);
            }
        });

        ddcb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ddcb.setText("Cà phê đen đá");
        ddcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddcbActionPerformed(evt);
            }
        });

        sdcb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sdcb.setText("Cà phê sữa đặc");
        sdcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdcbActionPerformed(evt);
            }
        });

        mccb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mccb.setText("Cà phê Mocha");
        mccb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mccbActionPerformed(evt);
            }
        });

        banhcb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        banhcb.setText("Bánh Flan");
        banhcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banhcbActionPerformed(evt);
            }
        });

        cpsl.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        cpsl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cpslStateChanged(evt);
            }
        });

        ddsl.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        ddsl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ddslStateChanged(evt);
            }
        });

        banhsl.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        banhsl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                banhslStateChanged(evt);
            }
        });

        mcsl.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        mcsl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mcslStateChanged(evt);
            }
        });

        sdsl.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        sdsl.setToolTipText("");
        sdsl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sdslStateChanged(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("(12.000 ₫)");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("(14.000 ₫)");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("(16.000 ₫)");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("(18.000 ₫)");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("(20.000 ₫)");

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gt1.setLabelFor(cpcb);
        gt1.setText("0");
        gt1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("₫");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("₫");

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gt2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gt2.setLabelFor(cpcb);
        gt2.setText("0");
        gt2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("₫");

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gt3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gt3.setLabelFor(cpcb);
        gt3.setText("0");
        gt3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt3, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gt4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gt4.setLabelFor(cpcb);
        gt4.setText("0");
        gt4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt4, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("₫");

        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gt0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gt0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gt0.setLabelFor(cpcb);
        gt0.setText("0");
        gt0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt0, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
            .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(gt0)))
        );

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setText("₫");

        javax.swing.GroupLayout panelcapLayout = new javax.swing.GroupLayout(panelcap);
        panelcap.setLayout(panelcapLayout);
        panelcapLayout.setHorizontalGroup(
            panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcapLayout.createSequentialGroup()
                .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcapLayout.createSequentialGroup()
                        .addComponent(ddcb)
                        .addGap(52, 52, 52)
                        .addComponent(ddsl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcapLayout.createSequentialGroup()
                        .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelcapLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mccb)
                                    .addComponent(banhcb))
                                .addGap(53, 53, 53)
                                .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(banhsl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mcsl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)))
                            .addGroup(panelcapLayout.createSequentialGroup()
                                .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelcapLayout.createSequentialGroup()
                                        .addComponent(sdcb)
                                        .addGap(36, 36, 36))
                                    .addComponent(cpcb, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sdsl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelcapLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cpsl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17))))
                        .addGap(5, 5, 5)
                        .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelcapLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(panelcapLayout.createSequentialGroup()
                                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28))
                            .addGroup(panelcapLayout.createSequentialGroup()
                                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26)))))
                .addContainerGap())
        );
        panelcapLayout.setVerticalGroup(
            panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcapLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddcb)
                    .addGroup(panelcapLayout.createSequentialGroup()
                        .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ddsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(1, 1, 1))
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sdsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sdcb)
                        .addComponent(jLabel17))
                    .addComponent(jLabel26)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelcapLayout.createSequentialGroup()
                        .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cpsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18))
                            .addComponent(cpcb)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelcapLayout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mccb)
                                        .addComponent(mcsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19)))
                                .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcapLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(banhcb)
                        .addComponent(banhsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20))
                    .addGroup(panelcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel29)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        getContentPane().add(panelcap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 490, 290));

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        hoadon.setColumns(20);
        hoadon.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        hoadon.setRows(5);
        jScrollPane1.setViewportView(hoadon);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 510, 580));

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Giá nước:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Phí dịch vụ:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Thế/VAT(10%):");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Tổng tiền tạm tính:");

        gianuoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gt10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gt10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gt10.setLabelFor(cpcb);
        gt10.setText("0");
        gt10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout gianuocLayout = new javax.swing.GroupLayout(gianuoc);
        gianuoc.setLayout(gianuocLayout);
        gianuocLayout.setHorizontalGroup(
            gianuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
            .addGroup(gianuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt10, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
        );
        gianuocLayout.setVerticalGroup(
            gianuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
            .addGroup(gianuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gt11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gt11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gt11.setLabelFor(cpcb);
        gt11.setText("0");
        gt11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt11, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gt13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gt13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gt13.setLabelFor(cpcb);
        gt13.setText("0");
        gt13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt13, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gt12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gt12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gt12.setLabelFor(cpcb);
        gt12.setText("0");
        gt12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt12, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gt12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("₫");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("₫");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("₫");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("₫");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(gianuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gianuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 380, 290));
        getContentPane().add(ddsl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mycbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycbActionPerformed
        // TODO add your handling code here:
        if (mycb.isSelected()) {
            tdsl.setEnabled(true);
            tt[5] = (int) tdsl.getValue() * 15000;
            gt5.setText(String.format("%,d\n", tt[5]));

        }
        if (!mycb.isSelected()) {
            tdsl.setEnabled(false);
            tdsl.setValue(1);
            gt5.setText("0");
            tt[5] = 0;
        }
    }//GEN-LAST:event_mycbActionPerformed

    private void banhcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banhcbActionPerformed
        // TODO add your handling code here:
        if (banhcb.isSelected()) {
            banhsl.setEnabled(true);
            tt[4] = (int) banhsl.getValue() * 20000;
            gt4.setText(String.format("%,d\n", tt[4]));
        }
        if (!banhcb.isSelected()) {
            banhsl.setEnabled(false);
            banhsl.setValue(1);
            gt4.setText("0");
            tt[4] = 0;
        }
    }//GEN-LAST:event_banhcbActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        hoadon.setText(null);
        ddcb.setSelected(false);
        ddsl.setValue(1);

        sdcb.setSelected(false);
        sdsl.setValue(1);
        cpcb.setSelected(false);
        cpsl.setValue(1);
        mccb.setSelected(false);
        mcsl.setValue(1);
        banhcb.setSelected(false);
        banhsl.setValue(1);
        mycb.setSelected(false);
        tdsl.setValue(1);
        buncb.setSelected(false);
        tssl.setValue(1);
        cscb.setSelected(false);
        stsl.setValue(1);
        htcb.setSelected(false);
        nesl.setValue(1);
        stingcb.setSelected(false);
        xxsl.setValue(1);
        ktcb.setSelected(false);
        ktsl.setValue(0);
        ddsl.setEnabled(false);
        sdsl.setEnabled(false);
        cpsl.setEnabled(false);
        mcsl.setEnabled(false);
        banhsl.setEnabled(false);
        tdsl.setEnabled(false);
        tssl.setEnabled(false);
        stsl.setEnabled(false);
        nesl.setEnabled(false);
        xxsl.setEnabled(false);
        ktsl.setEnabled(false);

        int i;
        for (i = 0; i < 10; i++) {
            tt[i] = 0;
        }

        gt0.setText("0");
        gt1.setText("0");
        gt2.setText("0");
        gt3.setText("0");
        gt4.setText("0");
        gt5.setText("0");
        gt6.setText("0");
        gt7.setText("0");
        gt8.setText("0");
        gt9.setText("0");
        gt10.setText("0");
        gt11.setText("0");
        gt12.setText("0");
        gt13.setText("0");
        gt14.setText("0");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        hoadon.setEditable(false);
        ddsl.setEnabled(false);
        sdsl.setEnabled(false);
        cpsl.setEnabled(false);
        mcsl.setEnabled(false);
        banhsl.setEnabled(false);
        tdsl.setEnabled(false);
        tssl.setEnabled(false);
        stsl.setEnabled(false);
        nesl.setEnabled(false);
        xxsl.setEnabled(false);
        ktsl.setEnabled(false);


    }//GEN-LAST:event_formComponentShown

    private void ddcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddcbActionPerformed
        if (ddcb.isSelected()) {
            ddsl.setEnabled(true);
            tt[0] = (int) ddsl.getValue() * 12000;

            gt0.setText(String.format("%,d\n", tt[0]));
        }
        if (!ddcb.isSelected()) {
            ddsl.setEnabled(false);
            ddsl.setValue(1);
            gt0.setText("0");
            tt[0] = 0;

        }
    }//GEN-LAST:event_ddcbActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tong.doClick();
        hoadon.setText(null);
        nuockt[0] = (int) ddsl.getValue();
        nuockt[1] = (int) sdsl.getValue();
        nuockt[2] = (int) cpsl.getValue();
        nuockt[3] = (int) mcsl.getValue();
        nuockt[4] = (int) banhsl.getValue();
        nuockt[5] = (int) tdsl.getValue();
        nuockt[6] = (int) tssl.getValue();
        nuockt[7] = (int) stsl.getValue();
        nuockt[8] = (int) nesl.getValue();
        nuockt[9] = (int) xxsl.getValue();
        nuockt[9] = (int) ktsl.getValue();

        Calendar time = Calendar.getInstance();
        time.getTime();
        SimpleDateFormat time1 = new SimpleDateFormat("HH:mm:ss");
        time1.format(time.getTime());
        SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
        date.format(time.getTime());

        hoadon.append("\t     ĐƠN HÀNG\n=================================\n");

        if (ddcb.isSelected()) {
            hoadon.append(
                    "Cà Phê đen đá(" + nuockt[0] + ")................\n" + tt[0] + "\n"
            );
        }
        if (sdcb.isSelected()) {
            hoadon.append(
                    "Cà Phê sữa đặc(" + nuockt[1] + ")...............\n" + tt[1] + "\n"
            );
        }
        if (cpcb.isSelected()) {
            hoadon.append(
                    "Cà Phê Cappuccino(" + nuockt[2] + ")............\n" + tt[2] + "\n"
            );
        }
        if (mccb.isSelected()) {
            hoadon.append(
                    "Cà Phê Mocha(" + nuockt[3] + ").................\n" + tt[3] + "\n"
            );
        }
        if (banhcb.isSelected()) {
            hoadon.append(
                    "Bánh Flan(" + nuockt[4] + ")..................\n" + tt[4] + "\n"
            );
        }
        if (mycb.isSelected()) {
            hoadon.append(
                    "Mỳ Bò(" + nuockt[5] + ").............\n" + tt[5] + "\n"
            );
        }
        if (buncb.isSelected()) {
            hoadon.append(
                    "Bún Thịt Nướng(" + nuockt[6] + ")............\n" + tt[6] + "\n"
            );
        }
        if (cscb.isSelected()) {
            hoadon.append(
                    "Cơm Sườn(" + nuockt[7] + ")..............\n" + tt[7] + "\n"
            );
        }
        if (htcb.isSelected()) {
            hoadon.append(
                    "Hủ Tiếu(" + nuockt[8] + ")..............\n" + tt[8] + "\n"
            );
        }
        if (stingcb.isSelected()) {
            hoadon.append(
                    "Sting Dâu(" + nuockt[9] + ")..........\n" + tt[9] + "\n"
            );
        }
        if (ktcb.isSelected()) {
            hoadon.append(
                    "Khẩu Trang(" + nuockt[10] + ")...................\n" + tt[15] + "\n"
            );
        }
        hoadon.append("=================================\nTổng tiền là: " + tt[16]);
        hoadon.append("\n=================================\nNgày:" + date.format(time.getTime()) + "\nGiờ:" + time1.format(time.getTime()) + "\n\n=================================\n\t   THANKS YOU\n");

        hoadon.append("*send to server*\n");
        hoadon.append("*wait for accept*");


    }//GEN-LAST:event_jButton3ActionPerformed

    private void sdcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdcbActionPerformed
        // TODO add your handling code here:
        if (sdcb.isSelected()) {
            sdsl.setEnabled(true);
            tt[1] = (int) sdsl.getValue() * 14000;
            gt1.setText(String.format("%,d\n", tt[1]));

        }
        if (!sdcb.isSelected()) {
            sdsl.setEnabled(false);
            sdsl.setValue(1);
            gt1.setText("0");
            tt[1] = 0;
        }


    }//GEN-LAST:event_sdcbActionPerformed

    private void cpcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpcbActionPerformed
        // TODO add your handling code here:
        if (cpcb.isSelected()) {
            cpsl.setEnabled(true);
            tt[2] = (int) cpsl.getValue() * 16000;
            gt2.setText(String.format("%,d\n", tt[2]));
        }
        if (!cpcb.isSelected()) {
            cpsl.setEnabled(false);
            cpsl.setValue(1);
            gt2.setText("0");
            tt[2] = 0;

        }
    }//GEN-LAST:event_cpcbActionPerformed

    private void mccbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mccbActionPerformed
        // TODO add your handling code here:
        if (mccb.isSelected()) {
            mcsl.setEnabled(true);
            tt[3] = (int) mcsl.getValue() * 18000;
            gt3.setText(String.format("%,d\n", tt[3]));
        }
        if (!mccb.isSelected()) {
            mcsl.setEnabled(false);
            mcsl.setValue(1);
            gt3.setText("0");
            tt[3] = 0;
        }
    }//GEN-LAST:event_mccbActionPerformed

    private void buncbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buncbActionPerformed
        // TODO add your handling code here:
        if (buncb.isSelected()) {
            tssl.setEnabled(true);
            tt[6] = (int) tssl.getValue() * 18000;
            gt6.setText(String.format("%,d\n", tt[6]));
        }
        if (!buncb.isSelected()) {
            tssl.setEnabled(false);
            tssl.setValue(1);
            gt6.setText("0");
            tt[6] = 0;
        }
    }//GEN-LAST:event_buncbActionPerformed

    private void cscbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cscbActionPerformed
        // TODO add your handling code here:
        if (cscb.isSelected()) {
            stsl.setEnabled(true);
            tt[7] = (int) stsl.getValue() * 16000;
            gt7.setText(String.format("%,d\n", tt[7]));
        }
        if (!cscb.isSelected()) {
            stsl.setEnabled(false);
            stsl.setValue(1);
            gt7.setText("0");
            tt[7] = 0;
        }
    }//GEN-LAST:event_cscbActionPerformed

    private void htcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htcbActionPerformed
        // TODO add your handling code here:
        if (htcb.isSelected()) {
            nesl.setEnabled(true);
            tt[8] = (int) nesl.getValue() * 14000;
            gt8.setText(String.format("%,d\n", tt[8]));
        }
        if (!htcb.isSelected()) {
            nesl.setEnabled(false);
            nesl.setValue(1);
            gt8.setText("0");
            tt[8] = 0;
        }
    }//GEN-LAST:event_htcbActionPerformed

    private void stingcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stingcbActionPerformed
        // TODO add your handling code here:
        if (stingcb.isSelected()) {
            xxsl.setEnabled(true);
            tt[9] = (int) xxsl.getValue() * 10000;
            gt9.setText(String.format("%,d\n", tt[9]));
        }
        if (!stingcb.isSelected()) {
            xxsl.setEnabled(false);
            xxsl.setValue(1);
            gt9.setText("0");
            tt[9] = 0;

        }
    }//GEN-LAST:event_stingcbActionPerformed

    private void ktcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ktcbActionPerformed
        // TODO add your handling code here:
        if (ktcb.isSelected()) {
            ktsl.setEnabled(true);
            ktsl.setValue(1);
            nuockt[10] = (int) ktsl.getValue();
        }
        if (!ktcb.isSelected()) {
            ktsl.setEnabled(false);
            ktsl.setValue(0);

        }
    }//GEN-LAST:event_ktcbActionPerformed

    private void ddslStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ddslStateChanged
        tt[0] = (int) ddsl.getValue() * 12000;
        gt0.setText(String.format("%,d\n", tt[0]));
    }//GEN-LAST:event_ddslStateChanged

    private void tongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tongActionPerformed
        tt[16] = (int) ktsl.getValue() * 1000;
        int i;
        tt[10] = 0;
        tt[11] =0;
        for (i = 0; i < 10; i++) {
            tt[10] = tt[10] + tt[i];
        }
        gt10.setText(String.format("%,d\n", tt[10]));
        if(tt[10]==0) tt[11]=0;
                else tt[11]=2000;
        gt11.setText(String.format("%,d\n", tt[11]));
        tt[12] = ((tt[10] + tt[11]) * 10 / 100) + ((tt[10] + tt[11]) % 10 / 100);
        gt12.setText(String.format("%,d\n", tt[12]));
        tt[13] = tt[10] + tt[11] + tt[12];
        gt13.setText(String.format("%,d\n", tt[13]));
        nuockt[10] = (int) ktsl.getValue();
        tt[15] = nuockt[10] * 1000;
        tt[16] = tt[15]/*khau trang*/ + tt[10]/*tong nuoc*/ + tt[11] + tt[12];
        gt14.setText(String.format("%,d\n", tt[16]));
        tt[10] = 0;
    }//GEN-LAST:event_tongActionPerformed

    private void sdslStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sdslStateChanged
        tt[1] = (int) sdsl.getValue() * 14000;
        gt1.setText(String.format("%,d\n", tt[1]));
    }//GEN-LAST:event_sdslStateChanged

    private void cpslStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cpslStateChanged
        tt[2] = (int) cpsl.getValue() * 16000;
        gt2.setText(String.format("%,d\n", tt[2]));
    }//GEN-LAST:event_cpslStateChanged

    private void mcslStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mcslStateChanged
        tt[3] = (int) mcsl.getValue() * 18000;
        gt3.setText(String.format("%,d\n", tt[3]));
    }//GEN-LAST:event_mcslStateChanged

    private void banhslStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_banhslStateChanged
        tt[4] = (int) banhsl.getValue() * 20000;
        gt4.setText(String.format("%,d\n", tt[4]));
    }//GEN-LAST:event_banhslStateChanged

    private void tdslStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tdslStateChanged
        tt[5] = (int) tdsl.getValue() * 15000;
        gt5.setText(String.format("%,d\n", tt[5]));
    }//GEN-LAST:event_tdslStateChanged

    private void tsslStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tsslStateChanged
        tt[6] = (int) tssl.getValue() * 18000;
        gt6.setText(String.format("%,d\n", tt[6]));
    }//GEN-LAST:event_tsslStateChanged

    private void stslStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_stslStateChanged
        tt[7] = (int) stsl.getValue() * 16000;
        gt7.setText(String.format("%,d\n", tt[7]));
    }//GEN-LAST:event_stslStateChanged

    private void neslStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_neslStateChanged
        tt[8] = (int) nesl.getValue() * 14000;
        gt8.setText(String.format("%,d\n", tt[8]));
    }//GEN-LAST:event_neslStateChanged

    private void xxslStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_xxslStateChanged
        tt[9] = (int) xxsl.getValue() * 10000;
        gt9.setText(String.format("%,d\n", tt[9]));
    }//GEN-LAST:event_xxslStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new main1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox banhcb;
    private javax.swing.JSpinner banhsl;
    private javax.swing.JCheckBox buncb;
    private javax.swing.JCheckBox cpcb;
    private javax.swing.JSpinner cpsl;
    private javax.swing.JCheckBox cscb;
    private javax.swing.JCheckBox ddcb;
    private javax.swing.JSpinner ddsl;
    private javax.swing.JSpinner ddsl2;
    private javax.swing.JPanel gianuoc;
    private javax.swing.JLabel gt0;
    private javax.swing.JLabel gt1;
    private javax.swing.JLabel gt10;
    private javax.swing.JLabel gt11;
    private javax.swing.JLabel gt12;
    private javax.swing.JLabel gt13;
    private javax.swing.JLabel gt14;
    private javax.swing.JLabel gt2;
    private javax.swing.JLabel gt3;
    private javax.swing.JLabel gt4;
    private javax.swing.JLabel gt5;
    private javax.swing.JLabel gt6;
    private javax.swing.JLabel gt7;
    private javax.swing.JLabel gt8;
    private javax.swing.JLabel gt9;
    private javax.swing.JTextArea hoadon;
    private javax.swing.JCheckBox htcb;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox ktcb;
    private javax.swing.JSpinner ktsl;
    private javax.swing.JCheckBox mccb;
    private javax.swing.JSpinner mcsl;
    private javax.swing.JCheckBox mycb;
    private javax.swing.JSpinner nesl;
    private javax.swing.JPanel panelcap;
    private javax.swing.JCheckBox sdcb;
    private javax.swing.JSpinner sdsl;
    private javax.swing.JCheckBox stingcb;
    private javax.swing.JSpinner stsl;
    private javax.swing.JSpinner tdsl;
    private javax.swing.JButton tong;
    private javax.swing.JSpinner tssl;
    private javax.swing.JSpinner xxsl;
    // End of variables declaration//GEN-END:variables
}
